"""站点设置注册表：所有可调项都在这里声明一次，后台自动渲染。"""
from __future__ import annotations

SETTING_GROUPS: list[dict[str, str]] = [
    {"key": "site", "name": "站点信息", "description": "站点名称、Logo、描述等基础信息", "icon": "globe"},
    {"key": "appearance", "name": "外观布局", "description": "主题色、首页模块、轮播与页脚", "icon": "palette"},
    {"key": "account", "name": "注册与登录", "description": "注册开关、用户名规则与登录安全", "icon": "user-plus"},
    {"key": "user", "name": "用户与权限", "description": "等级、经验、硬币与个人主页可见性", "icon": "users"},
    {"key": "video", "name": "视频与投稿", "description": "投稿限制、审核策略、播放器默认值", "icon": "film"},
    {"key": "comment", "name": "评论与弹幕", "description": "评论、弹幕开关与内容限制", "icon": "message-square"},
    {"key": "community", "name": "社区与互动", "description": "关注、私信、举报与通知策略", "icon": "heart"},
    {"key": "moderation", "name": "内容审核", "description": "敏感词、审核流程与违规处理", "icon": "shield-check"},
    {"key": "storage", "name": "存储与上传", "description": "文件体积、格式与目录策略", "icon": "hard-drive"},
    {"key": "security", "name": "安全防护", "description": "限流、验证码与维护模式", "icon": "shield"},
    {"key": "maintenance", "name": "备份与维护", "description": "自动备份、日志清理与缓存", "icon": "database"},
    {"key": "legal", "name": "页脚与协议", "description": "备案号、版权信息与用户协议", "icon": "scale"},
    {"key": "transcode", "name": "转码与清晰度", "description": "ffmpeg 转码、多清晰度与 HLS", "icon": "film"},
    {"key": "mail", "name": "邮件 / SMTP", "description": "SMTP 发信、验证码与邮件通知", "icon": "mail"},
    {"key": "oauth", "name": "第三方登录", "description": "GitHub / Gitee / Google / 自定义 OAuth2", "icon": "key-round"},
    {"key": "member", "name": "会员与充电", "description": "会员套餐、充值、充电与支付方式", "icon": "crown"},
    {"key": "live", "name": "直播", "description": "开播权限、推流与播放地址、聊天设置", "icon": "radio"},
    {"key": "infra", "name": "缓存与分布式", "description": "Redis 缓存、在线人数与限流", "icon": "server"},
    {"key": "sms", "name": "短信 / 手机号", "description": "短信服务商、验证码与手机号登录策略", "icon": "phone"},
    {"key": "pay", "name": "支付渠道", "description": "微信支付 v3 与支付宝（RSA2）参数、回调地址", "icon": "card"},
]


def _f(key: str, label: str, type_: str, default, group: str, **extra) -> dict:
    field = {"key": key, "label": label, "type": type_, "default": default, "group": group}
    field.update(extra)
    return field


SETTINGS: list[dict] = [
    # ------------------------------------------------------------------ 站点
    _f("site_name", "站点名称", "string", "PhotonV", "site", public=True),
    _f("site_full_name", "站点全称", "string", "PhotonV 微视频平台", "site", public=True),
    _f("site_description", "站点描述", "string", "一个开源、简洁、功能完整的微视频平台", "site", public=True),
    _f("site_keywords", "SEO 关键词", "string", "PhotonV,微视频,开源,视频平台", "site", public=True),
    _f("site_logo", "站点 Logo", "image", "", "site", public=True, upload_category="brand"),
    _f("site_favicon", "站点图标", "image", "", "site", public=True, upload_category="brand"),
    _f("beian", "备案号", "string", "", "site", public=True),
    _f("github_url", "开源仓库地址", "string", "https://github.com/x4ce-organization/PhotonV", "site", public=True),
    # ---------------------------------------------------------------- 外观
    _f("theme_color", "主题色", "color", "#00a1d6", "appearance", public=True),
    _f("default_theme_mode", "默认配色", "select", "light", "appearance", public=True,
       options=[{"value": "light", "label": "浅色"}, {"value": "dark", "label": "深色"}]),
    _f("enable_dark_mode", "允许切换深色模式", "boolean", True, "appearance", public=True),
    _f("layout_width", "页面宽度", "select", "wide", "appearance", public=True,
       options=[{"value": "wide", "label": "宽屏"}, {"value": "normal", "label": "标准"}]),
    _f("show_home_carousel", "首页显示轮播图", "boolean", True, "appearance", public=True),
    _f("home_carousel_interval", "轮播切换间隔（秒）", "number", 5, "appearance", public=True, min=2, max=20),
    _f("home_notice", "首页公告条", "string", "欢迎来到 PhotonV，上传你的第一条视频吧！", "appearance", public=True),
    _f("home_recommend_count", "首页推荐位数量", "number", 24, "appearance", public=True, min=6, max=60),
    _f("home_ranking_size", "首页排行榜条数", "number", 10, "appearance", public=True, min=5, max=20),
    _f("show_home_ranking", "首页显示排行榜", "boolean", True, "appearance", public=True),
    _f("footer_text", "页脚文字", "string", "Powered by PhotonV", "appearance", public=True),
    _f("copyright", "版权信息", "string", "© 2026 X4CE", "appearance", public=True),
    # ------------------------------------------------------------ 注册登录
    _f("allow_register", "开放注册", "boolean", True, "account", public=True),
    _f("register_need_email", "注册需要邮箱", "boolean", False, "account", public=True,
       description="不勾选时邮箱为选填，用户之后可以在「个人设置」里自行绑定"),
    _f("phone_required_register", "注册需要手机号", "boolean", False, "account", public=True,
       description="不勾选时手机号为选填，用户之后可以在「个人设置」里自行绑定；需要验证码与否由「短信 / 手机号」里的开关决定"),
    _f("register_email_suffix", "允许的邮箱后缀（JSON 数组，留空不限）", "json", [], "account"),
    _f("register_need_invite", "注册需要邀请码", "boolean", False, "account"),
    _f("invite_code", "注册邀请码", "string", "", "account"),
    _f("default_role", "新用户默认角色", "select", "user", "account",
       options=[{"value": "user", "label": "普通用户"}, {"value": "admin", "label": "管理员"}]),
    _f("username_min_length", "用户名最短长度", "number", 3, "account", public=True, min=1, max=32),
    _f("username_max_length", "用户名最长长度", "number", 20, "account", public=True, min=4, max=64),
    _f("password_min_length", "密码最短长度", "number", 8, "account", public=True, min=6, max=64),
    _f("session_days", "登录有效期（天）", "number", 14, "account", min=1, max=365),
    _f("login_fail_limit", "登录失败锁定次数", "number", 10, "account", min=0, max=100),
    _f("login_lock_minutes", "锁定时长（分钟）", "number", 15, "account", min=1, max=1440),
    _f("allow_change_username", "允许用户修改用户名", "boolean", False, "account", public=True),
    # --------------------------------------------------------------- 用户
    _f("allow_user_homepage", "开启个人主页", "boolean", True, "user", public=True),
    _f("default_private", "新用户默认隐藏收藏/关注", "boolean", False, "user"),
    _f("allow_follow", "开启关注功能", "boolean", True, "user", public=True),
    _f("allow_message", "开启私信", "boolean", True, "user", public=True),
    _f("coins_on_register", "注册赠送硬币", "number", 5, "user", min=0, max=1000),
    _f("coins_per_day", "每日登录赠送硬币", "number", 1, "user", min=0, max=100),
    _f("level_exp_step", "每级所需经验", "number", 200, "user", min=10, max=100000),
    _f("level_names", "等级名称", "json",
       ["Lv0 新星", "Lv1 微光", "Lv2 追光", "Lv3 星光", "Lv4 极光", "Lv5 曙光", "Lv6 光子"], "user"),
    _f("user_page_size", "用户列表分页", "number", 24, "user", public=True, min=6, max=100),
    # --------------------------------------------------------------- 视频
    _f("allow_upload", "开放投稿", "boolean", True, "video", public=True),
    _f("upload_min_level", "投稿所需等级", "number", 0, "video", public=True, min=0, max=6),
    _f("video_need_review", "投稿需要审核后公开", "boolean", True, "video", public=True),
    _f("video_review_note", "投稿页审核说明", "text",
       "投稿后需要等待管理员审核，审核通过即会自动公开。请确保内容原创、不含违规信息。", "video", public=True),
    _f("video_title_max", "标题最大长度", "number", 80, "video", public=True, min=10, max=200),
    _f("video_desc_max", "简介最大长度", "number", 2000, "video", public=True, min=100, max=20000),
    _f("video_tags_max", "最多标签数量", "number", 10, "video", public=True, min=1, max=30),
    _f("video_page_size", "列表每页数量", "number", 24, "video", public=True, min=4, max=100),
    _f("video_upload_interval", "两次投稿最小间隔（秒）", "number", 60, "video", min=0, max=86400),
    _f("video_daily_limit", "每日投稿上限", "number", 10, "video", min=0, max=1000),
    _f("video_extensions", "允许的视频格式", "json", ["mp4", "webm", "mov", "mkv", "m4v"], "video"),
    _f("image_extensions", "允许的图片格式", "json", ["jpg", "jpeg", "png", "webp", "gif", "svg"], "video"),
    _f("allow_download", "允许下载视频", "boolean", True, "video", public=True),
    _f("player_autoplay", "播放器自动播放", "boolean", True, "video", public=True),
    _f("player_default_quality", "默认清晰度", "select", "auto", "video", public=True,
       options=[{"value": "auto", "label": "自动"}, {"value": "high", "label": "高清"}]),
    _f("view_count_once_per_user", "同一用户重复播放不重复计数", "boolean", True, "video"),
    _f("video_exp_per_view", "每次播放给作者的经验", "number", 1, "video", min=0, max=100),
    # ------------------------------------------------------------ 评论弹幕
    _f("enable_comment", "开启评论", "boolean", True, "comment", public=True),
    _f("comment_max_length", "评论最大长度", "number", 500, "comment", public=True, min=10, max=5000),
    _f("comment_interval", "评论最小间隔（秒）", "number", 5, "comment", min=0, max=600),
    _f("comment_order", "评论默认排序", "select", "hot", "comment", public=True,
       options=[{"value": "hot", "label": "最热"}, {"value": "new", "label": "最新"}]),
    _f("comment_page_size", "评论每页数量", "number", 20, "comment", public=True, min=5, max=100),
    _f("comment_need_review", "评论需要审核", "boolean", False, "comment"),
    _f("enable_danmaku", "开启弹幕", "boolean", True, "comment", public=True),
    _f("danmaku_max_length", "弹幕最大长度", "number", 60, "comment", public=True, min=5, max=200),
    _f("danmaku_interval", "弹幕最小间隔（秒）", "number", 3, "comment", min=0, max=600),
    _f("danmaku_font_size", "弹幕默认字号（px）", "number", 18, "comment", public=True, min=12, max=32,
       description="建议 16-20，太大容易挡画面"),
    _f("danmaku_opacity", "弹幕默认不透明度（%）", "number", 85, "comment", public=True, min=10, max=100),
    _f("danmaku_speed", "弹幕滚动速度（秒）", "number", 8, "comment", public=True, min=4, max=20),
    # --------------------------------------------------------------- 社区
    _f("notify_reply", "回复时通知", "boolean", True, "community"),
    _f("notify_like", "被点赞时通知", "boolean", True, "community"),
    _f("notify_follow", "被关注时通知", "boolean", True, "community"),
    _f("notify_coin", "被投币时通知", "boolean", True, "community"),
    _f("notify_review", "投稿审核结果通知", "boolean", True, "community"),
    _f("allow_report", "允许举报", "boolean", True, "community", public=True),
    _f("report_reasons", "举报理由", "json",
       [{"value": "spam", "label": "垃圾广告"}, {"value": "porn", "label": "色情低俗"},
        {"value": "violence", "label": "暴力血腥"}, {"value": "copyright", "label": "侵权盗用"},
        {"value": "politics", "label": "违法违规"}, {"value": "other", "label": "其他"}], "community", public=True),
    _f("allow_share", "显示分享按钮", "boolean", True, "community", public=True),
    # ----------------------------------------------------------- 内容审核
    _f("banned_words", "敏感词（JSON 数组）", "json", [], "moderation"),
    _f("title_need_review", "标题命中敏感词直接驳回", "boolean", True, "moderation"),
    _f("auto_block_reported", "被举报达到阈值自动隐藏", "boolean", False, "moderation"),
    _f("report_hide_threshold", "自动隐藏的举报数阈值", "number", 5, "moderation", min=1, max=100),
    _f("banned_usernames", "保留用户名（JSON 数组）", "json", ["admin", "root", "system", "photonv"], "moderation"),
    # --------------------------------------------------------------- 存储
    _f("max_video_mb", "单个视频体积上限（MB）", "number", 2048, "storage", min=1, max=20480),
    _f("max_image_mb", "单张图片体积上限（MB）", "number", 16, "storage", min=1, max=100),
    _f("allow_video_url", "允许投稿填写外部视频直链", "boolean", True, "storage", public=True),
    _f("keep_original", "保留原始视频文件", "boolean", True, "storage"),
    # --------------------------------------------------------------- 安全
    _f("maintenance_mode", "维护模式", "boolean", False, "security", public=True),
    _f("maintenance_message", "维护提示语", "string", "站点维护中，请稍后再来～", "security", public=True),
    _f("maintenance_allow_admin", "维护时允许管理员访问", "boolean", True, "security"),
    _f("rate_limit_per_minute", "每 IP 每分钟请求上限", "number", 1200, "security", min=60, max=100000),
    _f("enable_captcha", "开启验证码", "boolean", False, "security", public=True),
    _f("blocked_ips", "IP 黑名单（JSON 数组）", "json", [], "security"),
    _f("force_https", "强制 HTTPS", "boolean", False, "security"),
    _f("content_security_note", "内容安全提示", "text",
       "请勿上传违法违规内容，平台将依法处理并保留相关记录。", "security", public=True),
    # --------------------------------------------------------------- 维护
    _f("auto_backup", "自动备份数据库", "boolean", False, "maintenance"),
    _f("auto_backup_interval_hours", "自动备份间隔（小时）", "number", 24, "maintenance", min=1, max=720),
    _f("backup_keep", "备份保留份数", "number", 10, "maintenance", min=1, max=200),
    _f("audit_log", "记录管理操作日志", "boolean", True, "maintenance"),
    _f("login_log_keep_days", "登录日志保留天数", "number", 90, "maintenance", min=1, max=3650),
    _f("home_cache_seconds", "首页缓存时间（秒）", "number", 10, "maintenance", min=0, max=600),
    # --------------------------------------------------------------- 协议
    _f("about_text", "关于我们", "text",
       "PhotonV 是一个完全开源的微视频平台，支持投稿、弹幕、评论、收藏与关注等功能。", "legal", public=True),
    _f("user_agreement", "用户协议", "text", "使用本站即表示同意遵守社区规范与相关法律法规。", "legal", public=True),
    _f("privacy_policy", "隐私政策", "text", "我们仅收集运行站点所必需的信息，不会向第三方出售用户数据。", "legal", public=True),
    _f("contact_email", "联系邮箱", "string", "", "legal", public=True),
]

SETTING_MAP: dict[str, dict] = {item["key"]: item for item in SETTINGS}
PUBLIC_KEYS: list[str] = [item["key"] for item in SETTINGS if item.get("public")]


# ---------------------------------------------------------------------------
# 转码 / 邮件 / 第三方登录 / 会员 / 直播 / 基础设施
# ---------------------------------------------------------------------------
_EXTRA: list[dict] = [
    # ------------------------------------------------------------- 转码
    _f("transcode_enabled", "上传后自动转码", "boolean", True, "transcode",
       description="关闭后只保存原文件，不生成多清晰度"),
    _f("transcode_hls", "生成 HLS 分片", "boolean", True, "transcode"),
    _f("transcode_keep_original", "保留原始视频文件", "boolean", True, "transcode"),
    _f("transcode_qualities", "生成的清晰度", "json", ["360p", "480p", "720p"], "transcode",
       description="可选 360p / 480p / 720p，源分辨率不足时自动跳过"),
    # ------------------------------------------------------------- 邮件
    _f("mail_enabled", "启用邮件服务", "boolean", False, "mail", public=True),
    _f("smtp_host", "SMTP 服务器", "string", "", "mail", placeholder="smtp.qq.com"),
    _f("smtp_port", "SMTP 端口", "number", 465, "mail", min=1, max=65535),
    _f("smtp_ssl", "使用 SSL（465）", "boolean", True, "mail"),
    _f("smtp_starttls", "使用 STARTTLS（587）", "boolean", True, "mail"),
    _f("smtp_user", "SMTP 用户名", "string", "", "mail"),
    _f("smtp_password", "SMTP 密码 / 授权码", "password", "", "mail", secret=True),
    _f("smtp_from", "发件人地址", "string", "", "mail"),
    _f("mail_from_name", "发件人显示名称", "string", "", "mail"),
    _f("mail_reply_to", "回复地址", "string", "", "mail"),
    _f("mail_allow_insecure_tls", "忽略 TLS 证书校验", "boolean", False, "mail"),
    _f("mail_throttle_seconds", "同一收件人发信间隔（秒）", "number", 60, "mail", min=0, max=86400),
    _f("mail_code_interval_seconds", "验证码重发间隔（秒）", "number", 60, "mail", min=10, max=3600),
    _f("mail_register_verify", "注册需要邮箱验证码", "boolean", False, "mail", public=True),
    _f("mail_reset_enabled", "允许邮箱找回密码", "boolean", True, "mail", public=True),
    _f("notify_mail_reply", "回复 / 评论邮件通知", "boolean", True, "mail"),
    _f("notify_mail_like", "点赞邮件通知", "boolean", False, "mail"),
    _f("notify_mail_coin", "投币邮件通知", "boolean", True, "mail"),
    _f("notify_mail_order", "订单状态邮件通知", "boolean", True, "mail"),
    _f("notify_mail_system", "系统通知邮件", "boolean", True, "mail"),
    # -------------------------------------------------------- 第三方登录
    _f("oauth_enabled", "启用第三方登录", "boolean", True, "oauth", public=True),
    _f("oauth_auto_register", "允许自动注册", "boolean", True, "oauth"),
    _f("oauth_allow_bind", "允许已登录用户绑定", "boolean", True, "oauth"),
    _f("oauth_bind_by_email", "按邮箱自动绑定已有账号", "boolean", True, "oauth"),
    _f("oauth_show_on_login", "登录页显示第三方按钮", "boolean", True, "oauth", public=True),
    _f("oauth_default_role", "自动注册用户角色", "select", "user", "oauth",
       options=[{"value": "user", "label": "普通用户"}, {"value": "admin", "label": "管理员"}]),
    _f("oauth_redirect_base", "回调地址前缀", "string", "", "oauth",
       description="留空则使用站点地址，例如 https://v.example.com"),
    _f("oauth_github_enabled", "启用 GitHub 登录", "boolean", False, "oauth", public=True),
    _f("oauth_github_client_id", "GitHub Client ID", "string", "", "oauth"),
    _f("oauth_github_client_secret", "GitHub Client Secret", "password", "", "oauth", secret=True),
    _f("oauth_github_authorize_url", "GitHub 授权地址", "string", "https://github.com/login/oauth/authorize", "oauth"),
    _f("oauth_github_token_url", "GitHub 令牌地址", "string", "https://github.com/login/oauth/access_token", "oauth"),
    _f("oauth_github_userinfo_url", "GitHub 用户信息地址", "string", "https://api.github.com/user", "oauth"),
    _f("oauth_github_scope", "GitHub Scope", "string", "read:user user:email", "oauth"),
    _f("oauth_gitee_enabled", "启用 Gitee 登录", "boolean", False, "oauth", public=True),
    _f("oauth_gitee_client_id", "Gitee Client ID", "string", "", "oauth"),
    _f("oauth_gitee_client_secret", "Gitee Client Secret", "password", "", "oauth", secret=True),
    _f("oauth_gitee_authorize_url", "Gitee 授权地址", "string", "https://gitee.com/oauth/authorize", "oauth"),
    _f("oauth_gitee_token_url", "Gitee 令牌地址", "string", "https://gitee.com/oauth/token", "oauth"),
    _f("oauth_gitee_userinfo_url", "Gitee 用户信息地址", "string", "https://gitee.com/api/v5/user", "oauth"),
    _f("oauth_gitee_scope", "Gitee Scope", "string", "user_info", "oauth"),
    _f("oauth_google_enabled", "启用 Google 登录", "boolean", False, "oauth", public=True),
    _f("oauth_google_client_id", "Google Client ID", "string", "", "oauth"),
    _f("oauth_google_client_secret", "Google Client Secret", "password", "", "oauth", secret=True),
    _f("oauth_google_authorize_url", "Google 授权地址", "string",
       "https://accounts.google.com/o/oauth2/v2/auth", "oauth"),
    _f("oauth_google_token_url", "Google 令牌地址", "string", "https://oauth2.googleapis.com/token", "oauth"),
    _f("oauth_google_userinfo_url", "Google 用户信息地址", "string",
       "https://www.googleapis.com/oauth2/v3/userinfo", "oauth"),
    _f("oauth_google_scope", "Google Scope", "string", "openid email profile", "oauth"),
    _f("oauth_custom_enabled", "启用自定义 OAuth2", "boolean", False, "oauth", public=True),
    _f("oauth_custom_client_id", "自定义 Client ID", "string", "", "oauth"),
    _f("oauth_custom_client_secret", "自定义 Client Secret", "password", "", "oauth", secret=True),
    _f("oauth_custom_authorize_url", "自定义授权地址", "string", "", "oauth"),
    _f("oauth_custom_token_url", "自定义令牌地址", "string", "", "oauth"),
    _f("oauth_custom_userinfo_url", "自定义用户信息地址", "string", "", "oauth"),
    _f("oauth_custom_scope", "自定义 Scope", "string", "user", "oauth"),
    # ---------------------------------------------------------- 会员与充电
    _f("membership_enabled", "开启会员", "boolean", True, "member", public=True),
    _f("membership_badge_text", "会员标识文字", "string", "大会员", "member", public=True),
    _f("membership_note", "会员权益说明", "text",
       "开通会员可获得专属标识、上传更大体积的视频、直播开播权限等。", "member", public=True),
    _f("recharge_enabled", "开启硬币充值", "boolean", True, "member", public=True),
    _f("coins_per_yuan", "每 1 元兑换硬币数", "number", 100, "member", public=True, min=1, max=10000),
    _f("charge_enabled", "开启充电（给 UP 主投币）", "boolean", True, "member", public=True),
    _f("charge_ratio", "充电兑换比例（多少硬币 = 1 元）", "number", 100, "member", public=True, min=1, max=10000),
    _f("creator_share_percent", "创作者分成（%）", "number", 70, "member", min=0, max=100),
    _f("pay_methods", "可用支付方式", "json",
       [{"value": "manual", "label": "人工审核 / 转账"}, {"value": "alipay", "label": "支付宝"},
        {"value": "wxpay", "label": "微信支付"}], "member", public=True),
    _f("pay_manual_note", "人工支付说明", "text",
       "下单后请联系管理员并提供订单号，管理员确认收款后订单会变为已支付。", "member", public=True),
    # ------------------------------------------------------------- 直播
    _f("live_enabled", "开启直播", "boolean", True, "live", public=True),
    _f("live_need_approval", "开播需要管理员开通权限", "boolean", True, "live"),
    _f("live_member_only", "仅会员可开播", "boolean", False, "live"),
    _f("live_push_base", "推流地址前缀", "string", "rtmp://localhost/live", "live",
       description="配合 nginx-rtmp / SRS 使用，主播用「前缀/流密钥」推流"),
    _f("live_play_base", "播放地址前缀", "string", "http://localhost:8080/live", "live",
       description="HLS 播放地址前缀，例如 http://你的域名/live"),
    _f("live_notice", "直播页提示", "text",
       "开播前请先申请直播权限，推流地址在直播间设置里可以看到。", "live", public=True),
    _f("live_chat_interval", "聊天最小间隔（秒）", "number", 2, "live", min=0, max=600),
    _f("live_chat_max_length", "聊天内容长度上限", "number", 100, "live", public=True, min=10, max=500),
    _f("live_max_hours", "单场直播最长时长（小时）", "number", 12, "live", min=1, max=72),
    # -------------------------------------------------------- 缓存与分布式
    _f("cache_home_seconds", "首页缓存时间（秒）", "number", 10, "infra", min=0, max=600),
    _f("cache_meta_seconds", "元数据缓存时间（秒）", "number", 60, "infra", min=0, max=3600),
    _f("online_window_seconds", "在线人数统计窗口（秒）", "number", 300, "infra", min=60, max=3600),
    # ------------------------------------------------------- 短信 / 手机号
    _f("sms_enabled", "启用短信服务", "boolean", False, "sms", public=True,
       description="关闭时验证码会写入站内信（开发模式），不会真的发短信"),
    _f("sms_provider", "短信服务商", "select", "dev", "sms",
       options=[{"value": "dev", "label": "开发模式（不真发短信）"}, {"value": "aliyun", "label": "阿里云短信"},
                {"value": "tencent", "label": "腾讯云短信"}, {"value": "custom", "label": "自定义 HTTP 网关"}]),
    _f("sms_sign_name", "短信签名", "string", "", "sms", placeholder="例如：PhotonV"),
    _f("sms_template_code", "短信模板（阿里云 TemplateCode / 腾讯云 TemplateId）", "string", "", "sms"),
    _f("sms_aliyun_key_id", "阿里云 AccessKeyId", "string", "", "sms"),
    _f("sms_aliyun_key_secret", "阿里云 AccessKeySecret", "password", "", "sms", secret=True),
    _f("sms_tencent_secret_id", "腾讯云 SecretId", "string", "", "sms"),
    _f("sms_tencent_secret_key", "腾讯云 SecretKey", "password", "", "sms", secret=True),
    _f("sms_tencent_sdk_app_id", "腾讯云 SmsSdkAppId", "string", "", "sms"),
    _f("sms_custom_url", "自定义网关地址", "string", "", "sms", placeholder="https://sms.example.com/send"),
    _f("sms_custom_body", "自定义请求体模板", "text",
       '{"phone":"{phone}","code":"{code}","sign":"{sign}"}', "sms",
       description="可用占位符：{phone} {code} {sign} {template}"),
    _f("sms_custom_success_key", "自定义网关成功标识（响应里包含该字符串即视为成功）", "string", '""ok":true', "sms"),
    _f("sms_code_length", "验证码位数", "number", 6, "sms", min=4, max=8),
    _f("sms_code_ttl_minutes", "验证码有效期（分钟）", "number", 10, "sms", min=1, max=60),
    _f("sms_code_interval", "验证码发送间隔（秒）", "number", 60, "sms", min=10, max=3600),
    _f("sms_daily_limit", "每个手机号每日发送上限", "number", 10, "sms", min=1, max=100),
    _f("sms_dev_expose_code", "开发模式下把验证码返回给前端", "boolean", False, "sms",
       description="仅本地调试时打开；生产环境请保持关闭，验证码只会写进日志与站内信"),
    _f("phone_login_enabled", "允许手机号 + 验证码登录", "boolean", True, "sms", public=True),
    _f("phone_register_verify", "注册时手机号需要验证码", "boolean", True, "sms", public=True,
       description="勾选「注册需要手机号」时会用到；关闭则只记录号码不校验"),
    _f("phone_required_bind", "必须绑定手机号才能投稿 / 评论", "boolean", False, "sms", public=True),
    _f("phone_mask", "前台隐藏手机号中间四位", "boolean", True, "sms", public=True),
    # --------------------------------------------------------------- 支付
    _f("pay_enabled", "启用在线支付", "boolean", False, "pay", public=True,
       description="关闭时只能用人工审核 / 转账"),
    _f("pay_return_url", "支付完成跳转地址", "string", "", "pay",
       placeholder="留空则使用站点地址 + /membership"),
    _f("pay_poll_seconds", "订单状态轮询间隔（秒）", "number", 3, "pay", public=True, min=1, max=30),
    _f("alipay_enabled", "启用支付宝", "boolean", False, "pay", public=True),
    _f("alipay_app_id", "支付宝 AppId", "string", "", "pay"),
    _f("alipay_private_key", "支付宝应用私钥（PKCS8，一行或带换行都行）", "text", "", "pay", secret=True),
    _f("alipay_public_key", "支付宝公钥（用于回调验签）", "text", "", "pay", secret=True),
    _f("alipay_gateway", "支付宝网关", "string", "https://openapi.alipay.com/gateway.do", "pay"),
    _f("alipay_sign_type", "签名算法", "select", "RSA2", "pay",
       options=[{"value": "RSA2", "label": "RSA2（推荐）"}, {"value": "RSA", "label": "RSA"}]),
    _f("alipay_mode", "支付宝支付方式", "select", "page", "pay",
       options=[{"value": "page", "label": "电脑网站支付（跳转支付宝页面）"},
                {"value": "qr", "label": "当面付 / 扫码（站内显示二维码）"}]),
    _f("wechat_enabled", "启用微信支付", "boolean", False, "pay", public=True),
    _f("wechat_mchid", "微信支付商户号 mchid", "string", "", "pay"),
    _f("wechat_appid", "微信支付 AppId", "string", "", "pay"),
    _f("wechat_api_v3_key", "APIv3 密钥（32 位，用于回调解密）", "password", "", "pay", secret=True),
    _f("wechat_serial_no", "商户证书序列号", "string", "", "pay"),
    _f("wechat_private_key", "商户 API 私钥（apiclient_key.pem 内容）", "text", "", "pay", secret=True),
    _f("wechat_native_url", "微信支付下单地址", "string", "https://api.mch.weixin.qq.com/v3/pay/transactions/native", "pay"),
]

SETTINGS.extend(_EXTRA)
SETTING_MAP = {item["key"]: item for item in SETTINGS}
PUBLIC_KEYS = [item["key"] for item in SETTINGS if item.get("public")]
