"""站点设置注册表：所有可调项都在这里声明一次，后台自动渲染。"""
from __future__ import annotations

SETTING_GROUPS: list[dict[str, str]] = [
    {"key": "site", "name": "站点信息", "description": "站点名称、Logo、描述等基础信息", "icon": "globe"},
    {"key": "appearance", "name": "外观布局", "description": "主题色、首页模块、轮播与页脚", "icon": "palette"},
    {"key": "account", "name": "注册与登录", "description": "注册开关、用户名规则与登录安全", "icon": "user-plus"},
    {"key": "user", "name": "用户与权限", "description": "等级、经验、硬币与个人主页可见性", "icon": "users"},
    {"key": "video", "name": "视频与投稿", "description": "投稿限制、审核策略、播放器默认值", "icon": "film"},
    {"key": "comment", "name": "评论与弹幕", "description": "评论、弹幕开关与内容限制", "icon": "message-square"},
    {"key": "community", "name": "社区与互动", "description": "关注、私信、举报与通知策略", "icon": "heart"},
    {"key": "moderation", "name": "内容审核", "description": "敏感词、审核流程与违规处理", "icon": "shield-check"},
    {"key": "storage", "name": "存储与上传", "description": "文件体积、格式与目录策略", "icon": "hard-drive"},
    {"key": "security", "name": "安全防护", "description": "限流、验证码与维护模式", "icon": "shield"},
    {"key": "maintenance", "name": "备份与维护", "description": "自动备份、日志清理与缓存", "icon": "database"},
    {"key": "legal", "name": "页脚与协议", "description": "备案号、版权信息与用户协议", "icon": "scale"},
]


def _f(key: str, label: str, type_: str, default, group: str, **extra) -> dict:
    field = {"key": key, "label": label, "type": type_, "default": default, "group": group}
    field.update(extra)
    return field


SETTINGS: list[dict] = [
    # ------------------------------------------------------------------ 站点
    _f("site_name", "站点名称", "string", "PhotonV", "site", public=True),
    _f("site_full_name", "站点全称", "string", "PhotonV 微视频平台", "site", public=True),
    _f("site_description", "站点描述", "string", "一个开源、简洁、功能完整的微视频平台", "site", public=True),
    _f("site_keywords", "SEO 关键词", "string", "PhotonV,微视频,开源,视频平台", "site", public=True),
    _f("site_logo", "站点 Logo", "image", "", "site", public=True, upload_category="brand"),
    _f("site_favicon", "站点图标", "image", "", "site", public=True, upload_category="brand"),
    _f("beian", "备案号", "string", "", "site", public=True),
    _f("github_url", "开源仓库地址", "string", "https://github.com/x4ce-organization/PhotonV", "site", public=True),
    # ---------------------------------------------------------------- 外观
    _f("theme_color", "主题色", "color", "#00a1d6", "appearance", public=True),
    _f("default_theme_mode", "默认配色", "select", "light", "appearance", public=True,
       options=[{"value": "light", "label": "浅色"}, {"value": "dark", "label": "深色"}]),
    _f("enable_dark_mode", "允许切换深色模式", "boolean", True, "appearance", public=True),
    _f("layout_width", "页面宽度", "select", "wide", "appearance", public=True,
       options=[{"value": "wide", "label": "宽屏"}, {"value": "normal", "label": "标准"}]),
    _f("show_home_carousel", "首页显示轮播图", "boolean", True, "appearance", public=True),
    _f("home_carousel_interval", "轮播切换间隔（秒）", "number", 5, "appearance", public=True, min=2, max=20),
    _f("home_notice", "首页公告条", "string", "欢迎来到 PhotonV，上传你的第一条视频吧！", "appearance", public=True),
    _f("home_recommend_count", "首页推荐位数量", "number", 24, "appearance", public=True, min=6, max=60),
    _f("home_ranking_size", "首页排行榜条数", "number", 10, "appearance", public=True, min=5, max=20),
    _f("show_home_ranking", "首页显示排行榜", "boolean", True, "appearance", public=True),
    _f("footer_text", "页脚文字", "string", "Powered by PhotonV", "appearance", public=True),
    _f("copyright", "版权信息", "string", "© 2026 X4CE", "appearance", public=True),
    # ------------------------------------------------------------ 注册登录
    _f("allow_register", "开放注册", "boolean", True, "account", public=True),
    _f("register_need_email", "注册必须填邮箱", "boolean", False, "account", public=True),
    _f("register_email_suffix", "允许的邮箱后缀（JSON 数组，留空不限）", "json", [], "account"),
    _f("register_need_invite", "注册需要邀请码", "boolean", False, "account"),
    _f("invite_code", "注册邀请码", "string", "", "account"),
    _f("default_role", "新用户默认角色", "select", "user", "account",
       options=[{"value": "user", "label": "普通用户"}, {"value": "admin", "label": "管理员"}]),
    _f("username_min_length", "用户名最短长度", "number", 3, "account", public=True, min=1, max=32),
    _f("username_max_length", "用户名最长长度", "number", 20, "account", public=True, min=4, max=64),
    _f("password_min_length", "密码最短长度", "number", 8, "account", public=True, min=6, max=64),
    _f("session_days", "登录有效期（天）", "number", 14, "account", min=1, max=365),
    _f("login_fail_limit", "登录失败锁定次数", "number", 10, "account", min=0, max=100),
    _f("login_lock_minutes", "锁定时长（分钟）", "number", 15, "account", min=1, max=1440),
    _f("allow_change_username", "允许用户修改用户名", "boolean", False, "account", public=True),
    # --------------------------------------------------------------- 用户
    _f("allow_user_homepage", "开启个人主页", "boolean", True, "user", public=True),
    _f("default_private", "新用户默认隐藏收藏/关注", "boolean", False, "user"),
    _f("allow_follow", "开启关注功能", "boolean", True, "user", public=True),
    _f("allow_message", "开启私信", "boolean", True, "user", public=True),
    _f("coins_on_register", "注册赠送硬币", "number", 5, "user", min=0, max=1000),
    _f("coins_per_day", "每日登录赠送硬币", "number", 1, "user", min=0, max=100),
    _f("level_exp_step", "每级所需经验", "number", 200, "user", min=10, max=100000),
    _f("level_names", "等级名称", "json",
       ["Lv0 新星", "Lv1 微光", "Lv2 追光", "Lv3 星光", "Lv4 极光", "Lv5 曙光", "Lv6 光子"], "user"),
    _f("user_page_size", "用户列表分页", "number", 24, "user", public=True, min=6, max=100),
    # --------------------------------------------------------------- 视频
    _f("allow_upload", "开放投稿", "boolean", True, "video", public=True),
    _f("upload_min_level", "投稿所需等级", "number", 0, "video", public=True, min=0, max=6),
    _f("video_need_review", "投稿需要审核后公开", "boolean", True, "video", public=True),
    _f("video_review_note", "投稿页审核说明", "text",
       "投稿后需要等待管理员审核，审核通过即会自动公开。请确保内容原创、不含违规信息。", "video", public=True),
    _f("video_title_max", "标题最大长度", "number", 80, "video", public=True, min=10, max=200),
    _f("video_desc_max", "简介最大长度", "number", 2000, "video", public=True, min=100, max=20000),
    _f("video_tags_max", "最多标签数量", "number", 10, "video", public=True, min=1, max=30),
    _f("video_page_size", "列表每页数量", "number", 24, "video", public=True, min=4, max=100),
    _f("video_upload_interval", "两次投稿最小间隔（秒）", "number", 60, "video", min=0, max=86400),
    _f("video_daily_limit", "每日投稿上限", "number", 10, "video", min=0, max=1000),
    _f("video_extensions", "允许的视频格式", "json", ["mp4", "webm", "mov", "mkv", "m4v"], "video"),
    _f("image_extensions", "允许的图片格式", "json", ["jpg", "jpeg", "png", "webp", "gif", "svg"], "video"),
    _f("allow_download", "允许下载视频", "boolean", True, "video", public=True),
    _f("player_autoplay", "播放器自动播放", "boolean", True, "video", public=True),
    _f("player_default_quality", "默认清晰度", "select", "auto", "video", public=True,
       options=[{"value": "auto", "label": "自动"}, {"value": "high", "label": "高清"}]),
    _f("view_count_once_per_user", "同一用户重复播放不重复计数", "boolean", True, "video"),
    _f("video_exp_per_view", "每次播放给作者的经验", "number", 1, "video", min=0, max=100),
    # ------------------------------------------------------------ 评论弹幕
    _f("enable_comment", "开启评论", "boolean", True, "comment", public=True),
    _f("comment_max_length", "评论最大长度", "number", 500, "comment", public=True, min=10, max=5000),
    _f("comment_interval", "评论最小间隔（秒）", "number", 5, "comment", min=0, max=600),
    _f("comment_order", "评论默认排序", "select", "hot", "comment", public=True,
       options=[{"value": "hot", "label": "最热"}, {"value": "new", "label": "最新"}]),
    _f("comment_page_size", "评论每页数量", "number", 20, "comment", public=True, min=5, max=100),
    _f("comment_need_review", "评论需要审核", "boolean", False, "comment"),
    _f("enable_danmaku", "开启弹幕", "boolean", True, "comment", public=True),
    _f("danmaku_max_length", "弹幕最大长度", "number", 60, "comment", public=True, min=5, max=200),
    _f("danmaku_interval", "弹幕最小间隔（秒）", "number", 3, "comment", min=0, max=600),
    _f("danmaku_opacity", "弹幕默认不透明度（%）", "number", 90, "comment", public=True, min=10, max=100),
    _f("danmaku_speed", "弹幕滚动速度（秒）", "number", 8, "comment", public=True, min=4, max=20),
    # --------------------------------------------------------------- 社区
    _f("notify_reply", "回复时通知", "boolean", True, "community"),
    _f("notify_like", "被点赞时通知", "boolean", True, "community"),
    _f("notify_follow", "被关注时通知", "boolean", True, "community"),
    _f("notify_coin", "被投币时通知", "boolean", True, "community"),
    _f("notify_review", "投稿审核结果通知", "boolean", True, "community"),
    _f("allow_report", "允许举报", "boolean", True, "community", public=True),
    _f("report_reasons", "举报理由", "json",
       [{"value": "spam", "label": "垃圾广告"}, {"value": "porn", "label": "色情低俗"},
        {"value": "violence", "label": "暴力血腥"}, {"value": "copyright", "label": "侵权盗用"},
        {"value": "politics", "label": "违法违规"}, {"value": "other", "label": "其他"}], "community", public=True),
    _f("allow_share", "显示分享按钮", "boolean", True, "community", public=True),
    # ----------------------------------------------------------- 内容审核
    _f("banned_words", "敏感词（JSON 数组）", "json", [], "moderation"),
    _f("title_need_review", "标题命中敏感词直接驳回", "boolean", True, "moderation"),
    _f("auto_block_reported", "被举报达到阈值自动隐藏", "boolean", False, "moderation"),
    _f("report_hide_threshold", "自动隐藏的举报数阈值", "number", 5, "moderation", min=1, max=100),
    _f("banned_usernames", "保留用户名（JSON 数组）", "json", ["admin", "root", "system", "photonv"], "moderation"),
    # --------------------------------------------------------------- 存储
    _f("max_video_mb", "单个视频体积上限（MB）", "number", 2048, "storage", min=1, max=20480),
    _f("max_image_mb", "单张图片体积上限（MB）", "number", 16, "storage", min=1, max=100),
    _f("allow_video_url", "允许投稿填写外部视频直链", "boolean", True, "storage", public=True),
    _f("keep_original", "保留原始视频文件", "boolean", True, "storage"),
    # --------------------------------------------------------------- 安全
    _f("maintenance_mode", "维护模式", "boolean", False, "security", public=True),
    _f("maintenance_message", "维护提示语", "string", "站点维护中，请稍后再来～", "security", public=True),
    _f("maintenance_allow_admin", "维护时允许管理员访问", "boolean", True, "security"),
    _f("rate_limit_per_minute", "每 IP 每分钟请求上限", "number", 1200, "security", min=60, max=100000),
    _f("enable_captcha", "开启验证码", "boolean", False, "security", public=True),
    _f("blocked_ips", "IP 黑名单（JSON 数组）", "json", [], "security"),
    _f("force_https", "强制 HTTPS", "boolean", False, "security"),
    _f("content_security_note", "内容安全提示", "text",
       "请勿上传违法违规内容，平台将依法处理并保留相关记录。", "security", public=True),
    # --------------------------------------------------------------- 维护
    _f("auto_backup", "自动备份数据库", "boolean", False, "maintenance"),
    _f("auto_backup_interval_hours", "自动备份间隔（小时）", "number", 24, "maintenance", min=1, max=720),
    _f("backup_keep", "备份保留份数", "number", 10, "maintenance", min=1, max=200),
    _f("audit_log", "记录管理操作日志", "boolean", True, "maintenance"),
    _f("login_log_keep_days", "登录日志保留天数", "number", 90, "maintenance", min=1, max=3650),
    _f("home_cache_seconds", "首页缓存时间（秒）", "number", 10, "maintenance", min=0, max=600),
    # --------------------------------------------------------------- 协议
    _f("about_text", "关于我们", "text",
       "PhotonV 是一个完全开源的微视频平台，支持投稿、弹幕、评论、收藏与关注等功能。", "legal", public=True),
    _f("user_agreement", "用户协议", "text", "使用本站即表示同意遵守社区规范与相关法律法规。", "legal", public=True),
    _f("privacy_policy", "隐私政策", "text", "我们仅收集运行站点所必需的信息，不会向第三方出售用户数据。", "legal", public=True),
    _f("contact_email", "联系邮箱", "string", "", "legal", public=True),
]

SETTING_MAP: dict[str, dict] = {item["key"]: item for item in SETTINGS}
PUBLIC_KEYS: list[str] = [item["key"] for item in SETTINGS if item.get("public")]
